default: &default
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>

development:
  <<: *default
  channel_prefix: zealot_development

test:
  adapter: test

production:
  <<: *default
  channel_prefix: zealot_production