default: &default
  <% if (url = ENV['ZEALOT_POSTGRES_URL']) && !url.to_s.empty? %>
  url: <%= url %>
  <% else %>
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: <%= ENV['ZEALOT_POSTGRES_HOST'] || 'localhost' %>
  port: <%= ENV['ZEALOT_POSTGRES_PORT'] || '5432' %>
  username: <%= ENV['ZEALOT_POSTGRES_USERNAME'] || 'zealot' %>
  password: <%= ENV['ZEALOT_POSTGRES_PASSWORD'] || '' %>
  database: <%= (host = ENV['ZEALOT_POSTGRES_DB_NAME'] || 'zealot'; case ENV['RAILS_ENV'] when 'test' then "#{host}_test"; when 'production' then host else "#{host}_development"; end) %>
  sslmode: <%= ENV['ZEALOT_POSTGRES_SSLMODE'] || 'disable' %>
  <% end %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

cache:
  <<: *default
  database: cache
  migrations_paths: db/cache_migrate
